project:
  type: website

website:
  title: "Disciple Vibes"
  navbar:
    right:
      - href: index.qmd
        text: THE QUIZ
      - href: all_disciples.qmd
        text: LIST OF DISCIPLES
  search: false

format:
  html:
    theme: 
      - styles.scss
    toc: false
